### ISSUE TITLE
Conda version

### ISSUE THREAD

**Issue by JonEilers** [ISUgenomics/SequelTools#18]
Hi,
Just wondering if there are plans to create a conda package for SequelTools?

**Comment by aseetharam** [comment]
Hi @JonEilers:
Thanks for trying SequelTools. 
The dependencies of SequelTools are very simple (samtools, python, and R), and the program itself is a script that you can execute directly (without compiling). Thus, we think conda package for SequelTools is overkill. If you are interested in creating one, we will be glad to provide the information you need!

Thanks,

**Comment by JonEilers** [comment]
I agree installation is simple. However, I ran into strange dependency issues. See two different errors below. I never actually figured it why I was getting either of those errors other then removing and creating a new environment and reinstalling the packages eventually solved the problem. It might be helpful to list what specific versions you recommend for those three conda packages? 

```bash
SequelTools.sh -p a -n 30 -t Q -u /home/jon/Working_Files/sea_cuke_species_data/stichopus_chloronotus/pacbio/sra/SRR8499556/subFiles.txt
Beginning quality control function

Running in NO_SCRAPS mode
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/jon/Working_Files/sea_cuke_species_data/stichopus_chloronotus/SequelTools/Scripts/generateReadLenStats_noScraps.py", line 107, in <module>
    subMean = Mean(subReadLens)
  File "/home/jon/Working_Files/sea_cuke_species_data/stichopus_chloronotus/SequelTools/Scripts/generateReadLenStats_noScraps.py", line 37, in Mean
    mn = float(sum(listx)) / float(len(listx))
ZeroDivisionError: float division by zero
ERROR: Calculation of read length statistics failed!
```
and 

```bash
SequelTools.sh -p a -n 40 -t Q -u /home/jon/Working_Files/sea_cuke_species_data/stichopus_chloronotus/pacbio/sra/SRR8499555/subFiles.txt
Beginning quality control function

Running in NO_SCRAPS mode
/home/jon/miniconda3/envs/sequeltools/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
SequelTools has finished!
```

**Comment by aseetharam** [comment]
Could you please check your `samtools` installation? 
```
samtools --version
```
The SequelTools need functional samtools in its path for it to work.

Thanks,
